### PR TITLE
initial version of my buy feature

### PR DESCRIPTION
**Pull request by Alan-Ou**

### CODE REVIEW

**Comment by sahilbakshi98** [comment]
Hey, this looks good. I tested it out in codespaces as well. 

Just a small suggestion - 
The tests that you have written for purchasing a product in test_routes.py, all of them are grouped under one definition. You can split them into separate definitions and add the sad paths to the Testing Sad Paths sections, such as the test for purchasing a product out of stock or purchasing a product not found.

This will make them show up when you run green as well. As of now, green only shows one test with the message "It should purchase a Product" even though multiple tests are being run.

**Comment by sahilbakshi98** [comment]
@Leslielu7 @Xin123456Zx thoughts?

**Comment by sahilbakshi98** [comment]
Also, I didn't see any linting errors so that's great as well.

**Comment by Alan-Ou** [comment]
Fixed

**Review by sahilbakshi98 — APPROVED** [review]

**Pull request merged**
